--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabBiswajit/BankNote
build-by-default: true
branches:
- main
projects:
  BankNote:
    path: ""
    lint:
      phpstan: default
      compat: 8.0
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
        branch: master
...
