--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabBiswajit/BankNote
build-by-default: true
branches:
- main
projects:
  BankNote:
    path: ""
    lint: false
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^4.0.0
        branch: stable
...
