---
name: BankNote
main: Biswajit\BankNote\BankNote
version: 2.0.0
api: [5.0.0]
author: Biswajit
description: "Convert your money into secure banknotes with anti-duplication protection and configurable items"
website: "https://github.com/GabBiswajit/BankNote"

softdepend:
  - BedrockEconomy
  - EconomyAPI
  - FormAPI

commands:
  banknote:
    description: "Create or redeem banknotes"
    usage: "/banknote [amount|ui]"
    permission: banknote.use
    aliases: ["bn", "note"]
    
permissions:
  banknote.use:
    description: "Allows players to create and redeem banknotes"
    default: true
  banknote.admin:
    description: "Administrative permissions for banknote management"
    default: op
    children:
      - banknote.use
...
